# Пользователи
## Создать нового пользователя

POST http://localhost:3001/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@user.test",
  "password": "111111",
  "avatar": "avatar.jpg",
  "type": "pro"
}

###

## Проверить статус авторизации пользователя

GET http://localhost:3001/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAdXNlci50ZXN0IiwibmFtZSI6IlRlc3QgVXNlciIsImlkIjoiNjg3YTRmNzQzZjQ5MmMxY2JiODkzMTQ5IiwiaWF0IjoxNzUyODQ2MzA3LCJleHAiOjE3NTI4NDk5MDd9.DvI2wD6Y3f770I68jrMOn7IwL8H4Q7NsY3BKmTi9Qr8

###

###

## Авторизовать пользователя

POST http://localhost:3001/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@user.test",
  "password": "111111"
}

###

## Отправить изображение

POST http://localhost:3001/users/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< ./screen.png
--WebAppBoundary--

###
