# Предложения
## Получить список предложений
GET http://localhost:3001/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:3001/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAdXNlci50ZXN0IiwibmFtZSI6IlRlc3QgVXNlciIsImlkIjoiNjg3YTRmNzQzZjQ5MmMxY2JiODkzMTQ5IiwiaWF0IjoxNzUyODUzODA5LCJleHAiOjE3NTI4NTc0MDl9.jcPbGZ_68-acKpWDk4oNJnOj7YFQUtQGTx2k5BovkHw

{
  "name": "Тестовое премиум предложение",
  "description": "Подробное описание предложения",
  "city": "Paris",
  "photoPreview": "img-preview.jpg",
  "photos": ["img1.jpg", "img2.jpg", "img1.jpg", "img2.jpg", "img1.jpg", "img2.jpg"],
  "isPremium": true,
  "type": "apartment",
  "roomsCount": 2,
  "guestCount": 4,
  "price": 2000,
  "features": ["Breakfast"],
  "coordinates": {
    "lat": 50.8504,
    "lon": 4.34878
  }
}

###

##

## Получить детальную информацию по предложению
GET http://localhost:3001/offers/687a50523f492c1cbb89314d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAdXNlci50ZXN0IiwibmFtZSI6IlRlc3QgVXNlciIsImlkIjoiNjg3YTRmNzQzZjQ5MmMxY2JiODkzMTQ5IiwiaWF0IjoxNzUyODUzODA5LCJleHAiOjE3NTI4NTc0MDl9.jcPbGZ_68-acKpWDk4oNJnOj7YFQUtQGTx2k5BovkHw

###

## Обновить предложение
PATCH http://localhost:3001/offers/687a50523f492c1cbb89314d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAdXNlci50ZXN0IiwibmFtZSI6IlRlc3QgVXNlciIsImlkIjoiNjg3YTRmNzQzZjQ5MmMxY2JiODkzMTQ5IiwiaWF0IjoxNzUyODUzODA5LCJleHAiOjE3NTI4NTc0MDl9.jcPbGZ_68-acKpWDk4oNJnOj7YFQUtQGTx2k5BovkHw

{
  "description": "Обновленное описание предложения"
}

###

## Получить премиальные предложения в городе
GET http://localhost:3001/offers/premium/moscow HTTP/1.1
Content-Type: application/json

###

## Удалить предложение
DELETE http://localhost:3001/offers/687a6d56d6f673e7cbad7391 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAdXNlci50ZXN0IiwibmFtZSI6IlRlc3QgVXNlciIsImlkIjoiNjg3YTRmNzQzZjQ5MmMxY2JiODkzMTQ5IiwiaWF0IjoxNzUyODUxOTI4LCJleHAiOjE3NTI4NTU1Mjh9.T0rybbELAuVrQxIf9K4Y-kXzMfsCF8X5lMw_HYM1T-4

###
