# Предложения
## Получить список предложений
GET http://localhost:3001/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:3001/offers HTTP/1.1
Content-Type: application/json

{
  "name": "Тестовое предложение",
  "description": "Описание предложения",
  "city": "Paris",
  "photoPreview": "img-preview.jpg",
  "photos": ["img1.jpg", "img2.jpg"],
  "isFavorite": true,
  "isPremium": false,
  "type": "apartment",
  "roomsCount": 2,
  "guestCount": 4,
  "price": 2000,
  "features": ["Breakfast"],
  "coordinates": {
    "lat": 50.8504,
    "lon": 4.34878
  }
}

###
