# Избранное
## Получить список избранных предложений
GET http://localhost:3001/favorites HTTP/1.1
Content-Type: application/json

###

## Добавить в избранное

POST http://localhost:3001/favorites/685a799b02f35881181febff HTTP/1.1
Content-Type: application/json

###

## Удалить из избранного

DELETE http://localhost:3001/favorites/685a799b02f35881181febff HTTP/1.1
Content-Type: application/json

###
